
  let database = [
    {
        id:1,
     name: "Ali",
     age: 8,
     surname: "ragimzada",
     email: "Ali12@mail.ru",
   passw: "Aliwka2012",
 },
{
  id:2,
     name: "Ulviyye",
     age: 30,
     surname: "rahimova",
     email: "Ulviyye@hotmail.com",
   passw: "Ulviyye1989",
 },
{
    id:3,
     name: "Farhad",
     age: 33,
     surname: "rahimov",
     email: "Frahimov@mail.ru",
   passw: "farhad01",
 },
  {
      id: 4,
  name: "Sebine",
  age: 29,
  surname: "orucova",
  email: "Sebine@mail.ru",
passw: "Sebine212",
},
{
  id:5,
  name: "Turan",
  age: 30,
  surname: "Cabarov",
  email: "Turan@gmail.com",
passw: "Ulviyye1989",
},
{
   id:6,
  name: "Ayan",
  age: 3,
  surname: "Cabariva",
  email: "Ayan@mail.ru",
passw: "Ayan1212",
},
{
id:7,
name: "Akif",
age: 67,
surname: "orucov",
email: "Akif@gmail.com",
passw: "AKIF0001",
},
{
 id:8,
name: "Nazakat",
age: 57,
surname: "orucova",
email: "Nazakat@mail.ru",
passw: "Nazakat10291",
},
];